[libdefaults]
  default_realm = CERN.CH
  ticket_lifetime = 24h
  renew_lifetime = 7d
  forwardable = true
  proxiable = true

[realms]
  CERN.CH = {
    default_domain = cern.ch
    kpasswd_server = afskrb5m.cern.ch
    admin_server = afskrb5m.cern.ch
    kdc = cerndc.cern.ch
  }

[domain_realm]
  cern.ch = CERN.CH
  .cern.ch = CERN.CH
